import { ToastContainer } from "react-toastify";
import { cookies } from 'next/headers';
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();
  const token = cookieStore.get('accessToken')?.value;  
  // if(token){
      const response = await fetch(
        "https://api.freeapi.app/api/v1/ecommerce/profile",
        {
          method: "GET",
          headers: {
            accept: "application/json",
            Authorization: `${token}`,
          },
        }
      );
      const data = await response.json();
  // }
  return (
    <html lang="en">
      <body>
        <Navbar userData={data.data}/>
        {children}
        <Footer />
        <ToastContainer position="top-right" />
      </body>
    </html>
  );
}
